export const STORAGE_KEYS = {
  HIGH_SCORE: 'taht_highscore',
  SOUND_MUTED: 'sound-muted',
  LANGUAGE: 'ims_lang',
  DARK_MODE: 'ims_dark',
  AD_FREE: 'ad_free_purchased',
  SAVE_GAME: 'imuststay_savegame',
  SEEN_CARDS: 'ims_seen_cards',
  CARDS_KNOWLEDGE_SHOWN: 'ims_knowledge_shown',
  TUTORIAL_DECLINED: 'ims_tutorial_declined',
  CHAIN_CHOICE: 'ims_chain_choice',
  ELECTION_TUTORIAL_DONE: 'ims_election_tutorial_done',
  COUNTED_SAVE_TS: 'ims_counted_save_ts',
  SKILL_LEVELS: 'ims_skill_levels',
  CLAIMED_ACHIEVEMENTS: 'ims_claimed_achievements',
} as const;
