export const STORAGE_KEYS = {
  HIGH_SCORE: 'taht_highscore',
  SOUND_MUTED: 'sound-muted',
  LANGUAGE: 'ims_lang',
  DARK_MODE: 'ims_dark',
  AD_FREE: 'ad_free_purchased',
  ORTADOGU_PACK: 'has_ortadogu_pack',
  TOTAL_GAMES: 'ims_total_games',
  SAVE_GAME: 'imuststay_savegame',
  SEEN_CARDS: 'ims_seen_cards',
  CARDS_KNOWLEDGE_SHOWN: 'ims_knowledge_shown',
  TUTORIAL_DECLINED: 'ims_tutorial_declined',
  CHAIN_CHOICE: 'ims_chain_choice',
  ELECTION_TUTORIAL_DONE: 'ims_election_tutorial_done',
  COUNTED_SAVE_TS: 'ims_counted_save_ts',
  SKILL_LEVELS: 'ims_skill_levels',
  CLAIMED_ACHIEVEMENTS: 'ims_claimed_achievements',
  POST_GAME_TOUR_DONE: 'ims_post_game_tour_done',
  MUSIC_VOLUME: 'ims_music_vol',
  SFX_VOLUME: 'ims_sfx_vol',
  SHOW_FACTION_PCT: 'ims_show_faction_pct',
} as const;
